version: '3.5'
services:
  database:
    image: mysql:latest
    restart: always
    container_name: "database"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=openc
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root1234
  web:
    build: .
    links:
      - database
    container_name: OPENC-Service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=3306
      - DB_NAME=openc
      - DB_HOST=database
      - MYSQL_USER=root
      - MYSQL_USER_PASSWORD=root1234
      - JPA_SHOW_SQL=true
      #- SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database